import type { Airport, Flight, SourceStatus } from '@hangban/contracts';

export const airports: Airport[] = [
  {
    iata: 'PEK',
    icao: 'ZBAA',
    name: '北京首都国际机场',
    city: '北京',
    country: '中国',
    latitude: 40.0799,
    longitude: 116.6031,
    elevationM: 35,
    type: 'large_airport',
  },
  {
    iata: 'PVG',
    icao: 'ZSPD',
    name: '上海浦东国际机场',
    city: '上海',
    country: '中国',
    latitude: 31.1443,
    longitude: 121.8083,
    elevationM: 4,
    type: 'large_airport',
  },
  {
    iata: 'HND',
    icao: 'RJTT',
    name: '东京羽田机场',
    city: '东京',
    country: '日本',
    latitude: 35.5494,
    longitude: 139.7798,
    elevationM: 6,
    type: 'large_airport',
  },
  {
    iata: 'SIN',
    icao: 'WSSS',
    name: '新加坡樟宜机场',
    city: '新加坡',
    country: '新加坡',
    latitude: 1.3644,
    longitude: 103.9915,
    elevationM: 7,
    type: 'large_airport',
  },
  {
    iata: 'JFK',
    icao: 'KJFK',
    name: '纽约约翰·肯尼迪国际机场',
    city: '纽约',
    country: '美国',
    latitude: 40.6413,
    longitude: -73.7781,
    elevationM: 4,
    type: 'large_airport',
  },
  {
    iata: 'SZX',
    icao: 'ZGSZ',
    name: "Shenzhen Bao'an International Airport",
    city: 'Shenzhen',
    localizedCity: '深圳',
    country: 'CN',
    latitude: 22.6393,
    longitude: 113.8107,
    elevationM: 4,
    type: 'large_airport',
  },
];

type FlightSeed = Omit<Flight, 'observedAt'>;

const flightSeeds: FlightSeed[] = [
  {
    id: 'icao-780001',
    icao24: '780001',
    callsign: 'CA981',
    airline: '中国国际航空',
    aircraftType: 'Boeing 747-8',
    registration: 'B-2482',
    latitude: 47.2,
    longitude: 150.8,
    altitudeM: 10_668,
    groundSpeedKmh: 901,
    headingDeg: 68,
    verticalRateMpm: 64,
    freshness: 'live',
    confidence: 0.92,
    sources: ['demo', 'adsb-lol'],
    origin: 'PEK',
    destination: 'JFK',
    inferredFields: [],
    fieldSources: [],
  },
  {
    id: 'icao-a00002',
    icao24: 'a00002',
    callsign: 'UA858',
    airline: 'United Airlines',
    aircraftType: 'Boeing 777-300ER',
    latitude: 49.1,
    longitude: -164.4,
    altitudeM: 11_278,
    groundSpeedKmh: 889,
    headingDeg: 74,
    verticalRateMpm: 0,
    freshness: 'live',
    confidence: 0.9,
    sources: ['demo', 'opensky'],
    origin: 'PEK',
    destination: 'JFK',
    inferredFields: [],
    fieldSources: [],
  },
  {
    id: 'icao-780003',
    icao24: '780003',
    callsign: 'MU587',
    airline: '中国东方航空',
    aircraftType: 'Boeing 777-300ER',
    latitude: 45.5,
    longitude: 132.5,
    altitudeM: 10_972,
    groundSpeedKmh: 874,
    headingDeg: 61,
    verticalRateMpm: 12,
    freshness: 'live',
    confidence: 0.88,
    sources: ['demo'],
    origin: 'PEK',
    destination: 'JFK',
    inferredFields: [],
    fieldSources: [],
  },
  {
    id: 'icao-780004',
    icao24: '780004',
    callsign: 'CZ699',
    airline: '中国南方航空',
    aircraftType: 'Airbus A350-900',
    latitude: 53.2,
    longitude: -142.6,
    altitudeM: 10_363,
    groundSpeedKmh: 846,
    headingDeg: 79,
    verticalRateMpm: -18,
    freshness: 'live',
    confidence: 0.86,
    sources: ['demo', 'airplanes-live'],
    origin: 'PEK',
    destination: 'JFK',
    inferredFields: [],
    fieldSources: [],
  },
  {
    id: 'icao-780005',
    icao24: '780005',
    callsign: 'MU5102',
    airline: '中国东方航空',
    aircraftType: 'Airbus A321neo',
    latitude: 39.4,
    longitude: 118.1,
    altitudeM: 7_315,
    groundSpeedKmh: 742,
    headingDeg: 310,
    verticalRateMpm: -210,
    freshness: 'live',
    confidence: 0.94,
    sources: ['demo'],
    origin: 'PVG',
    destination: 'PEK',
    inferredFields: [],
    fieldSources: [],
  },
  {
    id: 'icao-780006',
    icao24: '780006',
    callsign: 'CZ3101',
    airline: '中国南方航空',
    aircraftType: 'Airbus A320',
    latitude: 40.7,
    longitude: 115.8,
    altitudeM: 4_572,
    groundSpeedKmh: 611,
    headingDeg: 121,
    verticalRateMpm: -340,
    freshness: 'live',
    confidence: 0.91,
    sources: ['demo'],
    origin: 'CAN',
    destination: 'PEK',
    inferredFields: [],
    fieldSources: [],
  },
  {
    id: 'icao-76a007',
    icao24: '76a007',
    callsign: 'SQ12',
    airline: 'Singapore Airlines',
    aircraftType: 'Airbus A350-900',
    latitude: 16.8,
    longitude: 115.2,
    altitudeM: 11_582,
    groundSpeedKmh: 923,
    headingDeg: 38,
    verticalRateMpm: 0,
    freshness: 'delayed',
    confidence: 0.8,
    sources: ['demo'],
    origin: 'SIN',
    destination: 'SFO',
    inferredFields: [],
    fieldSources: [],
  },
  {
    id: 'icao-86b008',
    icao24: '86b008',
    callsign: 'NH919',
    airline: 'All Nippon Airways',
    aircraftType: 'Boeing 787-9',
    latitude: 37.8,
    longitude: 134.9,
    altitudeM: 9_754,
    groundSpeedKmh: 835,
    headingDeg: 264,
    verticalRateMpm: 22,
    freshness: 'live',
    confidence: 0.89,
    sources: ['demo'],
    origin: 'HND',
    destination: 'PVG',
    inferredFields: [],
    fieldSources: [],
  },
];

export function createDemoFlights(now: Date = new Date()): Flight[] {
  return flightSeeds.map((flight) => ({ ...flight, observedAt: now.toISOString() }));
}

export function createDemoSourceStatuses(now: Date = new Date()): SourceStatus[] {
  return [
    { providerId: 'adsb-lol', state: 'healthy', lastSuccessAt: now.toISOString() },
    { providerId: 'opensky', state: 'healthy', lastSuccessAt: now.toISOString() },
    {
      providerId: 'airplanes-live',
      state: 'degraded',
      lastSuccessAt: new Date(now.getTime() - 45_000).toISOString(),
      message: '部分区域更新延迟',
    },
  ];
}
